CREATE VIEW ATOMFY2022_ALLDATA AS
SELECT 
 AWARD_DEPARTMENT_ID
, A76_ACTION
, AGENCY
, AIOB_FLAG
, AIRPORT_AUTHORITY
, AITYPE
, ALASKAN_NATIVE_CORPORATION
, APAOB_FLAG
, BAOB_FLAG
, BASE_AND_ALL_OPTIONS
, BUNDLED_CONTRACT_EXCEPTION
, CAGE_CODE
, CITY
, CLINGER_COHEN_PLAN_COMPLIANCE
, COMMUNITY_DEVELOPMENT_CORP
, COMMUNITY_CORP_OWNED_FIRM
, COMPLETION_DATE
, CONGRESSIONAL_DISTRICT
, CONSOLIDATED_CONTRACT
, CONTRACT_FOR_FOREIGN_ENTITY
, CONTRACTING_AGENCY_ID
, CONTRACTING_OFFICE_ID
, CONTRACTS
, CONTRACTS_GRANTS
, CORP_ENTITY_NOT_TAX_EXEMPT
, CORP_ENTITY_TAX_EXEMPT
, COST_OR_PRICING_DATA
, COUNCIL_OF_GOVERNMENTS
, COUNTRY_OF_ORIGIN
, COUNTY
, CURRENT_TOTAL_VALUE
, DATE_SIGNED
, DESCRIPTION_OF_REQUIREMENT
, DOLLARS_OBLIGATED
, DOMESTIC_SHELTER
, DOT_CERTIFIED_DISADV_BUS
, EDJVWOSB_FLAG
, EDUCATIONAL_INSTITUTION_FLAG
, EDWOSB_FLAG
, EFFECTIVE_DATE
, EMERGING_SMALL_BUSINESS_FLAG
, EST_ULTIMATE_COMPLETION_DATE
, EVALUATED_PREFERENCE
, EXTENT_COMPETED
, FED_BIZ_OPPS
, FEDERAL_GOVERNMENT_FLAG
, FIRM_8A_FLAG
, FIRM8A_JOINT_VENTURE
, FOR_PROFIT_ORGANIZATION
, FOREIGN_FUNDING
, FOREIGN_GOVERNMENT
, FOREIGN_OWNED_AND_LOCATED
, FOUNDATION
, FUNDING_AGENCY_ID
, FUNDING_OFFICE_ID
, GLOBAL_UEI_NUMBER
, GRANTS
, HAOB_FLAG
, HBCU_FLAG
, HIGHER_LEARNING
, HISPANIC_SERVICING_INSTITUTION
, HOSPITAL_FLAG
, HOUSING_PUBLIC_OR_TRIBAL
, HUBZONE_FLAG
, IDV_CONTRACT_TYPE
, IDV_DEPARTMENT_ID
, IDV_MODIFICATION_NUMBER
, IDV_MUL_OR_SINGLE_AWARD_IDC
, IDV_PIID
, INDIAN_TRIBE
, INHERENTLY_GOVERNMENTAL_CODE
, INTER_MUNICIPAL
, INTERNATIONAL_ORGANIZATION
, INTERSTATE_ENTITY
, IS_PERFOR_BASED_SER_ACQU
, JVWOSB_FLAG
, LABOR_SURPLUS_AREA_FIRM
, LAND_GRANT_COLLEGE_1862
, LAND_GRANT_COLLEGE_1890
, LAND_GRANT_COLLEGE_1994
, LAST_MODIFIED_DATE
, LIMITED_LIABILITY_CORPORATION
, LOCAL_AREA_SET_ASIDE
, LOCAL_GOVERNMENT_FLAG
, LOCAL_GOVERNMENT_OWNED
, MAJOR_PROGRAM_CODE
, MANUFACTURER_OF_GOODS
, MINORITY_INSTITUTION_FLAG
, MINORITY_OWNED_BUSINESS_FLAG
, MODIFICATION_NUMBER
, MULTIYEAR_CONTRACT
, MUNICIPALITY
, NAOB_FLAG
, NATIONAL_INTEREST_CODE
, NATIVE_HAWAIIAN_ORGANIZATION
, NONPROFIT_ORGANIZATION_FLAG
, NUMBER_OF_ACTIONS
, ORGANIZATIONAL_TYPE
, OTHER_MINORITY_OWNED
, OTHER_NOT_FOR_PROFIT_ORG
, PARTNERSHIP_OR_LLP
, PIID
, PLACE_OF_MANUFACTURE
, PLACE_OF_PERFORM_COUNTRY_CODE
, PLACE_OF_PERFORM_STATE_CODE
, PLACE_OF_PERFORM_ZIP_CODE
, PLANNING_COMMISSION
, PORT_AUTHORITY
, PRINCIPAL_NAICS_CODE
, PRIVATE_UNIVERSITY_OR_COLLEGE
, PRODUCT_OR_SERVICE_CODE
, PURCHASE_CARD_PAYMENT_METHOD
, REASON_FOR_MODIFICATION
, RECOVERED_MATERIAL_CLAUSES
, RESEARCH_AND_DEVELOPMENT
, SAAOB_FLAG
, SCHOOL_DISTRICT
, SCHOOL_OF_FORESTRY
, SDB
, SDB_FLAG
, SELFCERT_HUBZONE_JOINTVENTURE
, SMALL_AGRICULTURAL_COOPERATIVE
, SOLE_PROPREITORSHIP
, SOLICITATION_PROCEDURES
, SRDVOB_FLAG
, STATE_GOVERNMENT_FLAG
, SUBCHAPTER_S_CORPORATION
, SUBCONTRACT_PLAN
, TOTAL_OBLIGATIONS
, TOWNSHIP
, TRANSIT_AUTHORITY
, TRIBAL_COLLEGE
, TRIBAL_GOVERNMENT_FLAG
, TRIBALLY_OWNED
, TYPE_OF_CONTRACT_PRICING
, TYPE_OF_SET_ASIDE_SOURCE
, IDV_TYPE_OF_SET_ASIDE
, ULTIMATE_CONTRACT_VALUE
, US_GOVERNMENT_ENTITY
, USE_OF_EPA_PRODUCTS
, VENDOR_ADDRESS_CITY
, VENDOR_ADDRESS_LINE_1
, VENDOR_ADDRESS_STATE_NAME
, VENDOR_ADDRESS_ZIP_CODE
, VENDOR_CONGRESSIONAL_DISTRICT
, VENDOR_COUNTRY_CODE
, VENDOR_NAME
, VENDOR_PHONE_NUMBER
, VENDOR_UEI_NUMBER
, VETERAN_OWNED_FLAG
, VETERINARY_COLLEGE
, VETERINARY_HOSPITAL
, WALSH_HEALEY_ACT
, WOMEN_OWNED_FLAG
, WOSB_FLAG
, SHELTERED_WORKSHOP_FLAG
, TRANSACTION_NUMBER
, CONTINGENCY_OPS
, AWARD_COUNTRY_NAME
, AWARD_IDV_TYPE_DESCRIPTION
, BUNDLED_CONTRACT_EXCEPTION_DESC
, CLINGER_COHEN_ACT_DESC
, CO_BUS_SIZE_DETERMINATION
, CONSOLIDATED_CONTRACT_DESC
, CONTRACTING_AGENCY_NAME
, CONTRACTING_DEPARTMENT_ID
, CONTRACTING_DEPARTMENT_NAME
, CONTRACTING_OFFICE_NAME
, EVALUATED_PREFERENCE_DESC
, EXTENT_COMPETED_DESCRIPTION
, FED_BIZ_OPPS_DESC
, FOREIGN_FUNDING_DESCRIPTION
, FUNDING_AGENCY_NAME
, FUNDING_DEPARTMENT_ID
, FUNDING_DEPARTMENT_NAME
, FUNDING_OFFICE_NAME
, IDV_DEPARTMENT_NAME
, IDV_TYPE_DESCRIPTION
, INHERENTLY_GOVERNMENTAL_DESC
, LASA_DESCRIPTION
, MULTIYEAR_CONTRACT_DESC
, NATIONAL_INTEREST_DESCRIPTION
, PBSC_SHORT_DESCRIPTION
, PLACE_OF_PERFORM_COUNTRY_NAME
, POM_SHORT_DESCRIPTION
, POP_CITY
, POP_COUNTY_NAME
, POP_LOCATION_STATE_NAME
, PRINCIPAL_NAICS_DESCRIPTION
, PRODUCT_OR_SERVICE_DESCRIPTION
, REASON_FOR_MODIFICATION_DESC
, RECOVERED_MATERIAL_CLS_DESC
, SOLICITATION_PROCEDURES_DESC
, SUBCONTRACT_PLAN_DESC
, TOCP_SHORT_DESCRIPTION
, UNDEFINITIZED_ACTION_DESC
, VENDOR_ADDRESS_COUNTRY_NAME
, WALSH_HEALEY_ACT_DESC
, CONTRACT_FINANCING
, PRICE_EVAL_DIFF
, STATRY_EXPTN_TO_FAIR_OPRTNTY
, FAIR_OPRTNTY_DESC
, NUMBER_OF_OFFERS_RECEIVED
, SOLICITATION_ID
, TYPE_OF_SET_ASIDE
, TYPE_OF_SET_ASIDE_DESCRIPTION
, AWARD_OR_IDV
, CLAIMANT_PROGRAM_CODE
, SEA_TRANSPORTATION
, SYSTEM_EQUIP_CODE
, CLAIMANT_PROGRAM_DESCRIPTION
, COST_ACCT_STANDARDS
, SOLICITATION_DATE
, DOING_BUSINESS_AS_NAME
, OTHER_STATUTORY_AUTHORITY
, IT_COMMERCIAL_ITEM_CATEGORY
, RESEARCH
, RESEARCH_DESCRIPTION
, CCR_EXCEPTION_TYPE
, VENDOR_ADDRESS_LINE_2
, IDV_LAST_DATE_TO_ORDER
, MULTIPLE_OR_SINGLE_AWARD_IDC_CODE
, MULTIPLE_OR_SINGLE_AWARD_IDC
, TYPE_OF_IDC_CODE
, TYPE_OF_IDC
, PROGRAM_ACRONYM
, UNIQUE_ID

 -- Write in the calculated columns
 --- Small Business Dollars
 , CASE 
	WHEN CO_BUS_SIZE_DETERMINATION = 'SMALL BUSINESS' THEN DOLLARS_OBLIGATED
	ELSE 0
 END AS SMALL_BUSINESS_DOLLARS,

 --- SDB Dollars
 CASE 
	WHEN CO_BUS_SIZE_DETERMINATION = 'SMALL BUSINESS' AND (
		SDB_FLAG = 'true' OR
		SDB = 'true' OR
		FIRM_8A_FLAG = 'true' OR 
		FIRM8A_JOINT_VENTURE = 'true'
		) THEN DOLLARS_OBLIGATED
	ELSE 0
 END AS SDB_DOLLARS,

 --- WOSB Dollars
 CASE 
	WHEN CO_BUS_SIZE_DETERMINATION = 'SMALL BUSINESS' AND (
		EDWOSB_FLAG = 'true' OR
		EDJVWOSB_FLAG = 'true' OR
		WOSB_FLAG = 'true' OR
		JVWOSB_FLAG = 'true' OR
		WOMEN_OWNED_FLAG = 'true'
		) THEN DOLLARS_OBLIGATED
	ELSE 0
 END AS WOSB_DOLLARS,

 --- HUBZone Dollars
  CASE 
	WHEN CO_BUS_SIZE_DETERMINATION = 'SMALL BUSINESS' AND (
	HUBZONE_FLAG = 'true' OR
	SELFCERT_HUBZONE_JOINTVENTURE = 'true' 
		) THEN DOLLARS_OBLIGATED
	ELSE 0 
 END AS CER_HUBZONE_SB_DOLLARS,

 --- SDVOSBC Dollars
 CASE 
	WHEN CO_BUS_SIZE_DETERMINATION = 'SMALL BUSINESS' AND (
		SRDVOB_FLAG = 'true'
		) THEN DOLLARS_OBLIGATED
	ELSE 0 
 END AS SRDVOB_DOLLARS,

 --- 8(a) Dollars
 CASE
	WHEN CO_BUS_SIZE_DETERMINATION = 'SMALL BUSINESS' AND (
	TYPE_OF_SET_ASIDE IN ('8AN', '8A', 'HSC') OR IDV_TYPE_OF_SET_ASIDE IN ('8AN', '8A', 'HSC') 
			) THEN DOLLARS_OBLIGATED
	ELSE 0 
 END AS EIGHT_A_PROCEDURE_DOLLARS,

 -- SBGR column
 CASE 
	WHEN PIID IN ( -- - Department of Education's Not-for-Profit(NFP) Loan Servicing contracts listed below (Base and any Modification), plus any Award (Base or Modification) which references one of these contract numbers should be excluded. (data are excluded when the signed date is equal to or greater than October 1, 2013):
			 'EDFSA11D0012',
			 'EDFSA12D0003',
			 'EDFSA12D0005',
			 'EDFSA12D0006',
			 'EDFSA12D0007',
			 'EDFSA12D0012',
			 'EDFSA13D0001'
			 ) THEN 'NO'
	WHEN IDV_PIID IN (
			 'EDFSA11D0012',
			 'EDFSA12D0003',
			 'EDFSA12D0005',
			 'EDFSA12D0006',
			 'EDFSA12D0007',
			 'EDFSA12D0012',
			 'EDFSA13D0001'
			 ) THEN 'NO'
	WHEN SHELTERED_WORKSHOP_FLAG = 'true' THEN 'NO' -- Javits-Wagner-O'Day Program (The AbilityOne Program, Sheltered Workshop): Awards that have a contractor with a SAM based Sheltered Workshop designation Flag equal to "Y" are excluded.
	WHEN FOREIGN_FUNDING IN ('A', 'B') THEN 'NO' --  Acquisitions by agencies on behalf of foreign governments or entities or international organizations: Actions that are funded by foreign entities ("Funded by Foreign Entity" = 'Yes' OR "Foreign Funding" = 'Foreign Funds - FMS' or 'Foreign Funds - non-FMS') are excluded from the report.
	WHEN CONTRACTING_OFFICE_ID IN ('H94002', 'HT9402', '00NAF') THEN 'NO'
	WHEN VENDOR_UEI_NUMBER IN (       --UNICOR: Exclude the UNICOR Unique Entity IDs specified in APPENDIX A.
		 'Q9M6NBKH74G3', 
		 'SYLDKUFLV1H4', 
		 'DX5EKNZFA3N5', 
		 'DJNLDAUMKEJ5', 
		 'QSVDL5JLEEJ6', 
		 'JAMWLNJ9J5P6', 
		 'C8CLXN6LVNF8', 
		 'MH4CB9DKTNQ4', 
		 'W66EAQMDW725', 
		 'RY1UXHB1M1K5', 
		 'E8NTQR3CJEF8', 
		 'K1DNSJ1RT9A1', 
		 'DRDXM1XD2KK8', 
		 'TZYMUE5NK8M4', 
		 'T422H2MGNEP6', 
		 'KHFLCLB4BW91', 
		 'JQLDEL8SSF24', 
		 'NL9XTCND2B61', 
		 'S1NSFTYGMES9', 
		 'VSNRFJTTPMX6', 
		 'T1KSAHQRAAM7', 
		 'JKZXA7K7CJG2', 
		 'P95UX39ABTK7', 
		 'V4W9UULK21B7', 
		 'LKJLV1UHQNL8', 
		 'S118NFU2A4H3', 
		 'NS4GGWZGXJG8', 
		 'GCXKXNG653F9', 
		 'LHMZK6ZF6S87', 
		 'C8BXEEATNDL1', 
		 'HS2LL6F188B8', 
		 'Y6DKA9CH9HG8', 
		 'JG5ELMLTFKW3', 
		 'N1JBKE5TJ1J5', 
		 'EVKUQPQXME98', 
		 'XKK5YFSFYSS2', 
		 'CH2KGNMYKBZ4', 
		 'MH2LK48RW8K9', 
		 'C4KAFNUZUNJ9', 
		 'EB6TWP1VMZB5', 
		 'D5ENM348KWL9', 
		 'RLUNF7CEP6U6', 
		 'L2MHVK5MLVE3',
		 'Z4QSJZHMQZ28',
		 'MV2UKGNJRU25', 
		 'J4EEUF33BA75', 
		 'LMMMUEPESAL1', 
		 'QAW8DCW831M6', 
		 'HHXDFJHVQE43', 
		 'Z21JKYZ3S5B1', 
		 'UPCNMFE7BMM6'
		)   THEN 'NO'
	WHEN FUNDING_DEPARTMENT_ID = '9700' AND ( -- DOD Specific Resctictions
		CONTINGENCY_OPS = 'A' OR   -- - All records that have the value of Code A 'Contingency operation as defined in 10 U.S.C 101(a)(13)' for the Data Element "Emergency Acquisition" and the Funding Agency is DoD, and the Date Signed is equal to or greater than October 1, 2015.
		(CONTINGENCY_OPS = 'B' AND  -- - All records that have the value of Code 'B' 'Humanitarian or Peacekeeping Operation as defined in 10 U.S.C 2302(8)' for the Data Element "Emergency Acquisition" where the performance is outside of the USA and its territories, and the Funding Agency is DoD, and the Date Signed is equal to or greater than 10/01/2017.
			PLACE_OF_PERFORM_COUNTRY_NAME NOT IN ('UNITED STATES')) OR
		(CONTINGENCY_OPS = 'D' AND  -- - All records that have a value of Code 'D' 'Humanitarian and Civic assistance as Defined in 10 U.S.C 401(e)' for the Data Element "Emergency Acquisition" where the performance is outside of the USA and its territories, and the Funding Agency is DoD, and the Date Signed is equal to or greater than 6/26/2020.
			PLACE_OF_PERFORM_COUNTRY_NAME NOT IN ('UNITED STATES')) OR -- 
		(SYSTEM_EQUIP_CODE = 'ZSF' AND -- All records that have the value of Code 'ZSF' 'Status of Forces Agreements' for "DoD Acquisition Program", where the performance is outside of the USA and its territories, and the Funding Agency is DoD and the Date Signed is equal to or greater than 10/01/2017.
		    PLACE_OF_PERFORM_COUNTRY_NAME NOT IN ('UNITED STATES')) OR 
		PLACE_OF_PERFORM_COUNTRY_NAME IN (  'AFGHANISTAN', -- All records where the place of performance is equal to any country on the below list and the Funding Agency is DoD and the Date Signed is equal to or greater than 10/01/2017.
  'ALBANIA',
  'ARMENIA',
  'AUSTRALIA',
  'AUSTRIA',
  'AZERBAIJAN',
  'BELARUS',
  'BELGIUM',
  'BELIZE',
  'BENIN',
  'BOSNIA AND HERZEGOVINA',
  'BRAZIL',
  'BULGARIA',
  'BURKINA FASO',
  'BURUNDI',
  'CAMBODIA',
  'CAMEROON',
  'CANADA',
  'CENTRAL AFRICAN REPUBLIC',
  'CHAD',
  'COMOROS',
  'DEMOCRATIC REPUBLIC OF THE CONGO',
  'COTE D''IVOIRE',
  'CROATIA',
  'CUBA',
  'CYPRUS',
  'CZECH REPUBLIC',
  'DENMARK',
  'EL SALVADOR',
  'ESTONIA',
  'FINLAND',
  'FRANCE',
  'GABON',
  'GEORGIA',
  'GERMANY',
  'GHANA',
  'GREECE',
  'GRENADA',
  'GUATEMALA',
  'GUINEA',
  'GUYANA',
  'HAITI',
  'HONDURAS',
  'HUNGARY',
  'ICELAND',
  'IRAQ',
  'IRELAND',
  'ISRAEL',
  'ITALY',
  'JAPAN',
  'JORDAN',
  'KAZAKHSTAN',
  'KOREA',
  'KOSOVO',
  'KYRGYZSTAN',
  'LATVIA',
  'LIBERIA',
  'LITHUANIA',
  'LUXEMBOURG',
  'MACEDONIA',
  'MADAGASCAR',
  'MALI',
  'MALTA',
  'MOLDOVA',
  'MONTENEGRO',
  'MOZAMBIQUE',
  'NEPAL',
  'NETHERLANDS',
  'NICARAGUA',
  'NIGER',
  'NIGERIA',
  'NORWAY',
  'PANAMA',
  'PAPUA NEW GUINEA',
  'PHILIPPINES',
  'POLAND',
  'PORTUGAL',
  'ROMANIA',
  'RUSSIAN FEDERATION',
  'RWANDA',
  'SAINT KITTS AND NEVIS',
  'SAINT LUCIA',
  'SAMOA',
  'SENEGAL',
  'SERBIA',
  'SEYCHELLES',
  'SINGAPORE',
  'SLOVAKIA',
  'SLOVENIA',
  'SOLOMON ISLANDS',
  'SOUTH AFRICA',
  'SPAIN',
  'SRI LANKA',
  'SUDAN',
  'SURINAME',
  'SWAZILAND',
  'SWEDEN',
  'SWITZERLAND',
  'TAJIKISTAN ',
  'TIMOR-LESTE',
  'TONGA',
  'TRINIDAD AND TOBAGO',
  'TURKEY',
  'TURKMENISTAN',
  'UGANDA',
  'UKRAINE',
  'UNITED KINGDOM ',
  'UZBEKISTAN'
  ) OR
   (AWARD_COUNTRY_NAME  NOT IN ('USA') AND  -- -All contracts that have the 'Country Where Award was Issued' Code as other than USA or USA Territories (state codes AP, AE, and AA are treated as Other than USA); and the Place of Performance as other than USA or USA Territories, and the Funding Agency is DoD, and Date Signed is equal to or greater 10/01/2017.
   PLACE_OF_PERFORM_COUNTRY_NAME NOT IN ('UNITED STATES') ) 

	) THEN 'NO'
	ELSE 'YES'
 END AS SBGR,

 CASE 
	WHEN LOCAL_AREA_SET_ASIDE = 'Y' THEN 'YES'
	WHEN  VENDOR_ADDRESS_STATE_NAME IN ('PUERTO RICO',
      'GUAM',
      'VIRGIN ISLANDS OF THE U.S.',
      'AMERICAN SAMOA',
      'NORTHERN MARIANA ISLANDS'
	  ) THEN 'YES'
	ELSE 'NO'
 END AS DOUBLE_CREDIT

 -- And we are basing this all on the growing ATOM_ALLDATA table. In the future, we can do an FY22 and an FY23 version of it. 
 FROM ATOM_ALLDATA
 WHERE DATE_SIGNED < '2022-10-01'


